services:
  device-postgres-db:
    image: postgres:15.8
    container_name: dms-device-postgres-db
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'" ]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: always
    volumes:
      - ./device-postgres-db:/var/lib/postgresql/data
    networks:
      - dms-device-network
  device-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dms-device-service
    ports:
      - "${SERVICE_PORT}:8080"
    environment:
      ACTIVE_PROFILE: dev
      DB_HOST: device-postgres-db:5432
      ROOT_LOG_LEVEL: error
      WEB_LOG_LEVEL: debug
    #      ALLOW_ORIGIN: localhost
    env_file:
      - .env
    volumes:
      - ./logs:/dms-device/logs
    depends_on:
      device-postgres-db:
        condition: service_healthy
        restart: true
    networks:
      - dms-device-network
networks:
  dms-device-network: