services:
  device-postgres-db:
    image: postgres:15.8
    container_name: device-postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: device_service
    healthcheck:
#      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U admin -d device_service'" ]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: always
    volumes:
      - ./device-postgres-db:/var/lib/postgresql/data
    networks:
      - device-network
  device-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: device-service
    ports:
      - "8080:8080"
    environment:
      ACTIVE_PROFILE: test
      DB_HOST: camera-postgres-db:5432
      DB_NAME: device-service
      DB_USER: admin
      DB_PASSWORD: admin
      ROOT_LOG_LEVEL: error
      WEB_LOG_LEVEL: info
    volumes:
      - ./logs:/dms-device/logs
    depends_on:
      device-postgres-db:
        condition: service_healthy
        restart: true
    networks:
      - device-network
networks:
  device-network